[package]
name = "ecdar-gui-grpc-communication"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.10.2"

[build-dependencies]
tonic-build = "0.10.2"
